/* -*- C -*- */
/** ---------------------------------------------------------------------------
 * @file   cryoscope.cds
 * @brief  CDS/Deinterlace parameters for cryoscope instrument
 */

#include "mod10vcpu"   /* include the VCPU code for MOD10 */

BIGBUF=_ARCHON_FRAMEBUFS
FRAMEMODE=_ARCHON_FRAMEMODE
LINECOUNT=_TOTAL_ROWS      /* _CDS_LINES_PER_TAP */
PIXELCOUNT=_MAX_XADDR      /* _CDS_PIXELS_PER_TAP */
RAWENABLE=_RAW_ENABLE
RAWENDLINE=_RAW_ENDLINE
RAWSAMPLES=_RAW_SAMPLES
RAWSEL=_RAW_SELECT
RAWSTARTLINE=_RAW_STARTLINE
RAWSTARTPIXEL=_RAW_STARTPIXEL
SAMPLEMODE=_ARCHON_SAMPLE_MODE
SHP1=_FIRST_RESET_SAMPLE
SHP2=_LAST_RESET_SAMPLE
SHD1=_FIRST_VIDEO_SAMPLE
SHD2=_LAST_VIDEO_SAMPLE
TAPLINE0="AM54L,1,0"
TAPLINE1="AM25R,1,0"
TAPLINE2="AM29L,1,0"
TAPLINE3="AM31R,1,0"
TAPLINE4="AM52L,1,0"
TAPLINES=5
TRIGINEDGE=0
TRIGINENABLE=0
TRIGININVERT=0
TRIGOUTFORCE=0
TRIGOUTINVERT=0
TRIGOUTLEVEL=0
TRIGOUTPOWER=1
