name: Build all ACF files

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - name: Checkout code with submodule
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install gpp
      run: | 
        sudo apt-get update
        sudo apt-get install -y gpp
        python -m pip install --upgrade pip
        python -m pip install numpy
        python -m pip install matplotlib
    - name: Build ACF
      run: |
        cd src/cryoscope
        python ../bin/build_acf.py cryoscope
